spring:
  datasource:
    url: jdbc:h2:mem:bcm_db
    username: root
    password: root
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  sql:
    init:
      data-locations: classpath:schema.sql, classpath:data.sql
  security:
    user:
      password: root
      name: root
    filter:
      order: 10 #Permet d avoir 10 filter personnalisé qui seront prioritaires sur le filtre par defaut